/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    SkButton: typeof import('@skiyee/uni-ui/components/sk-button.vue')['default']
    SkIcon: typeof import('@skiyee/uni-ui/components/sk-icon.vue')['default']
    SkOverlay: typeof import('@skiyee/uni-ui/components/sk-overlay.vue')['default']
    SkRadio: typeof import('@skiyee/uni-ui/components/sk-radio.vue')['default']
    SkRadioGroup: typeof import('@skiyee/uni-ui/components/sk-radio-group.vue')['default']
    SkRoller: typeof import('@skiyee/uni-ui/components/sk-roller.vue')['default']
    SkRollerGroup: typeof import('@skiyee/uni-ui/components/sk-roller-group.vue')['default']
    SkTab: typeof import('@skiyee/uni-ui/components/sk-tab.vue')['default']
    SkTabItem: typeof import('@skiyee/uni-ui/components/sk-tab-item.vue')['default']
    SkTabs: typeof import('@skiyee/uni-ui/components/sk-tabs.vue')['default']
  }
}
